<a href="https://colab.research.google.com/github/Namachivayan/semantic-search-system/blob/main/project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.23.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [2]:
from datasets import load_dataset

# Load dataset
dataset = load_dataset("fancyzhx/ag_news")

print(dataset)

# Convert to pandas DataFrame
df = dataset["train"].to_pandas()

# Save as CSV
df.to_csv("ag_news_train.csv", index=False)

# Display first 5 rows
print(df.head())
df.columns
len(df)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/8.07k [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 18.6MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 1.23MB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/120000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/7600 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 120000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 7600
    })
})
                                                text  label
0  Wall St. Bears Claw Back Into the Black (Reute...      2
1  Carlyle Looks Toward Commercial Aerospace (Reu...      2
2  Oil and Economy Cloud Stocks' Outlook (Reuters...      2
3  Iraq Halts Oil Exports from Main Southern Pipe...      2
4  Oil prices soar to all-time record, posing new...      2

120000

In [3]:
label_map = {
    0: "World",
    1: "Sports",
    2: "Business",
    3: "Science & Technology"
}
df["document_id"] = range(1, len(df) + 1)
df["title"] = df["text"].str.split(".").str[0]
df[["title"]].head()
df["content"] = df["text"]
df[["content"]].head()
df["keywords"] = ""
df[["keywords"]].head()
df["category"] = df["label"].map(label_map) # Add this line to create the 'category' column
final_df = df[
    [
        "document_id",
        "category",
        "title",
        "content",
        "keywords"
    ]
]
final_df.head()

,document_id,category,title,content,keywords
0,1,Business,Wall St,Wall St. Bears Claw Back Into the Black (Reute...,
1,2,Business,Carlyle Looks Toward Commercial Aerospace (Reu...,Carlyle Looks Toward Commercial Aerospace (Reu...,
2,3,Business,Oil and Economy Cloud Stocks' Outlook (Reuters...,Oil and Economy Cloud Stocks' Outlook (Reuters...,
3,4,Business,Iraq Halts Oil Exports from Main Southern Pipe...,Iraq Halts Oil Exports from Main Southern Pipe...,
4,5,Business,"Oil prices soar to all-time record, posing new...","Oil prices soar to all-time record, posing new...",

In [4]:
final_df.to_csv("semantic_search_dataset.csv", index=False)

In [5]:
print(final_df.info())
print(final_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   document_id  120000 non-null  int64
 1   category     120000 non-null  object
 2   title        120000 non-null  object
 3   content      120000 non-null  object
 4   keywords     120000 non-null  object
dtypes: int64(1), object(4)
memory usage: 4.6+ MB
None
   document_id  category                                              title  \
0            1  Business                                            Wall St
1            2  Business  Carlyle Looks Toward Commercial Aerospace (Reu...
2            3  Business  Oil and Economy Cloud Stocks' Outlook (Reuters...
3            4  Business  Iraq Halts Oil Exports from Main Southern Pipe...
4            5  Business  Oil prices soar to all-time record, posing new...

                                             content keywords
0  Wall St. Bears Claw Back Into the Black (Reute...
1  Carlyle Looks Toward Commercial Aerospace (Reu...
2  Oil and Economy Cloud Stocks' Outlook (Reuters...
3  Iraq Halts Oil Exports from Main Southern Pipe...
4  Oil prices soar to all-time record, posing new...

In [6]:
import re
def clean_text(text):
    # Convert to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", "", text)

    # Remove HTML tags
    text = re.sub(r"<.*?>", "", text)

    # Keep only letters, numbers and spaces
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [7]:
final_df["content"] = final_df["content"].apply(clean_text)
final_df.head()

/tmp/ipykernel_689/1440747331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["content"] = final_df["content"].apply(clean_text)

,document_id,category,title,content,keywords
0,1,Business,Wall St,wall st bears claw back into the black reuters...,
1,2,Business,Carlyle Looks Toward Commercial Aerospace (Reu...,carlyle looks toward commercial aerospace reut...,
2,3,Business,Oil and Economy Cloud Stocks' Outlook (Reuters...,oil and economy cloud stocks outlook reuters r...,
3,4,Business,Iraq Halts Oil Exports from Main Southern Pipe...,iraq halts oil exports from main southern pipe...,
4,5,Business,"Oil prices soar to all-time record, posing new...",oil prices soar to all time record posing new ...,

In [8]:
!pip install keybert sentence-transformers

Collecting keybert
  Downloading keybert-0.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from keybert) (2.0.2)
Requirement already satisfied: rich>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from keybert) (13.9.4)
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.12/dist-packages (from keybert) (1.6.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.13.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.23.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cu128)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert) (2.20.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence-transformers) (1.5.6)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Downloading keybert-0.9.0-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.4/41.4 kB 2.2 MB/s eta 0:00:00
Installing collected packages: keybert
Successfully installed keybert-0.9.0

In [9]:
from keybert import KeyBERT
kw_model = KeyBERT()

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [10]:
text = final_df.loc[0, "content"]

keywords = kw_model.extract_keywords(
    text,
    keyphrase_ngram_range=(1,2),
    stop_words="english",
    top_n=5
)

print(keywords)

[('wall st', 0.5405), ('st bears', 0.5025), ('bears claw', 0.4437), ('wall street', 0.4275), ('sellers wall', 0.4273)]

In [11]:
keyword_list = [k[0] for k in keywords]

print(keyword_list)

['wall st', 'st bears', 'bears claw', 'wall street', 'sellers wall']

In [12]:
final_df.loc[0, "keywords"] = ", ".join(keyword_list)
final_df.head()

,document_id,category,title,content,keywords
0,1,Business,Wall St,wall st bears claw back into the black reuters...,"wall st, st bears, bears claw, wall street, se..."
1,2,Business,Carlyle Looks Toward Commercial Aerospace (Reu...,carlyle looks toward commercial aerospace reut...,
2,3,Business,Oil and Economy Cloud Stocks' Outlook (Reuters...,oil and economy cloud stocks outlook reuters r...,
3,4,Business,Iraq Halts Oil Exports from Main Southern Pipe...,iraq halts oil exports from main southern pipe...,
4,5,Business,"Oil prices soar to all-time record, posing new...",oil prices soar to all time record posing new ...,

In [13]:
for i in range(100):
    text = final_df.loc[i, "content"]

    keywords = kw_model.extract_keywords(
        text,
        keyphrase_ngram_range=(1,2),
        stop_words="english",
        top_n=5
    )

    keyword_list = [k[0] for k in keywords]

    final_df.loc[i, "keywords"] = ", ".join(keyword_list)

In [14]:
!pip install sentence-transformers faiss-cpu

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)
Collecting faiss-cpu
  Downloading faiss_cpu-1.15.0-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.13.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.23.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cu128)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence-transformers) (1.5.6)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Downloading faiss_cpu-1.15.0-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 50.6 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.15.0

In [15]:
from sentence_transformers import SentenceTransformer

In [16]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [17]:
print(df.columns)

Index(['text', 'label', 'document_id', 'title', 'content', 'keywords',
       'category'],
      dtype='object')

In [18]:
embedding = model.encode(df.loc[0, "content"])

print(embedding)

[ 7.43859494e-03  2.85623856e-02  4.10954878e-02  1.05001405e-01
  2.32820306e-02  3.51258591e-02 -2.14059930e-02 -2.29023080e-02
  4.94522322e-03 -6.68985620e-02 -5.93040325e-02  2.45948173e-02
 -5.12895510e-02 -4.04271595e-02  6.65567408e-04 -1.17221139e-02
 -4.34821891e-03  2.06902418e-02 -2.29348894e-03 -3.47106196e-02
 -8.01126659e-02 -6.02049828e-02 -2.86629219e-02 -1.86906159e-02
 -7.84591362e-02  4.60197292e-02 -4.96721193e-02 -3.33420373e-02
  5.32347448e-02 -1.26492038e-01 -7.07766935e-02 -6.30829774e-04
 -2.26125419e-02  2.00371374e-03  8.22302978e-03 -6.30246615e-03
  8.53442121e-03 -4.64320779e-02  4.35816124e-02  3.90969478e-02
  1.36761914e-03 -2.62946226e-02 -5.70246726e-02  3.29648294e-02
  1.93821136e-02  4.52637151e-02  5.92519119e-02  5.84027357e-02
 -2.66226032e-03 -3.10069490e-02  1.38102081e-02 -2.49957554e-02
 -3.08281183e-02  3.99599448e-02  2.42338702e-02  1.04000501e-03
  4.13026698e-02 -3.98771018e-02  1.06792070e-01 -5.37586324e-02
  8.35924968e-02  2.60991510e-02 -9.42061096e-03  3.85204963e-02
  5.00620231e-02  1.02082282e-01 -3.00723016e-02  4.86091338e-03
 -3.01296357e-02 -4.20883074e-02  8.49267617e-02  5.68141639e-02
  2.73304619e-02 -1.92071795e-02  2.98327822e-02  7.02265054e-02
  6.47178069e-02  9.14529804e-03 -4.41692509e-02 -1.43106198e-02
  4.67405468e-02 -4.48012091e-02 -1.01746328e-01  5.37886657e-02
  7.33288378e-02  3.61008979e-02 -5.68202846e-02 -4.22204100e-02
 -4.75793183e-02  3.76329944e-02 -1.88587829e-02  5.40658413e-03
 -2.50694901e-02  5.41584380e-02 -1.31447287e-02 -1.93552673e-02
 -1.82578489e-02 -8.17586482e-02  1.05918692e-02  1.60397179e-02
  1.50289917e-02  5.00059780e-03  3.29446532e-02  3.19348113e-03
 -1.23682022e-02 -6.88884705e-02 -5.05330861e-02  9.17498618e-02
  2.85667479e-02  1.13431569e-02 -8.19298075e-05  4.76496434e-03
 -1.91096328e-02 -6.00610673e-02 -4.16381657e-02 -2.16411445e-02
 -5.39709963e-02 -2.85705999e-02  2.91723106e-02 -9.83218383e-03
  5.61473146e-02  1.01567730e-01 -8.30661654e-02 -8.66538659e-02
 -7.28246272e-02 -7.38255307e-02  1.14452341e-04 -2.94560866e-33
  1.29513117e-02  3.29493009e-03 -2.69521251e-02 -1.27380207e-01
  5.91092221e-02  4.89585847e-02 -5.86830713e-02  5.55276265e-03
 -3.65704261e-02 -1.60690751e-02 -4.35909927e-02  1.30741699e-02
  1.01757934e-02 -3.13173197e-02 -3.97898220e-02 -1.08112127e-01
  2.10377034e-02  1.79145858e-02  1.98885589e-03  9.94461775e-03
 -2.88646370e-02  9.00590345e-02  1.58325175e-03  2.29997393e-02
  2.57764515e-02 -1.04951253e-02  4.36975844e-02  6.71092644e-02
  2.61567254e-02 -4.59924806e-03 -2.28354931e-02  3.69978957e-02
  3.39014865e-02  8.38253368e-03  2.86678504e-02 -1.14904838e-02
  1.62692051e-02 -1.05529120e-02  2.03754287e-02  6.43416587e-03
 -2.59774104e-02  3.54591236e-02 -5.50178774e-02  4.53422181e-02
  2.65623499e-02  2.67665368e-02  2.31892409e-04 -1.01790495e-01
 -8.09773430e-02 -4.44029756e-02  2.53114663e-02  6.51474148e-02
 -9.44346711e-02  4.40636352e-02  5.49461460e-03 -3.59069929e-02
  5.87427765e-02 -9.74870007e-03 -1.02629378e-01 -5.40196113e-02
  5.39265499e-02  1.22858025e-01  8.33591223e-02 -1.63270428e-03
 -1.77955702e-02  1.85302757e-02 -7.23801479e-02  1.06141403e-01
 -9.71800461e-02  2.66222917e-02 -6.51972601e-03  9.59842745e-03
  7.68384058e-03 -1.00001559e-01 -3.20982039e-02 -1.52576938e-02
 -2.68455315e-02  1.97346527e-02  7.19508752e-02  2.94931419e-03
  8.47932138e-03 -1.77736208e-02  4.28504534e-02  1.15431789e-02
 -3.88402463e-04  7.77245015e-02  3.56635377e-02 -1.04233719e-01
 -1.05899386e-02 -1.78102013e-02 -5.72639443e-02 -1.53902369e-02
 -5.22111403e-03 -6.65445998e-03 -6.45052940e-02 -6.90937350e-34
  7.61740434e-04 -4.69966978e-02  4.54329662e-02  1.67199802e-02
 -1.98323298e-02 -1.35377171e-02 -2.09184419e-02  3.32162865e-02
 -4.13968526e-02  3.15711871e-02 -2.35399865e-02  3.67998630e-02
  3.71506001e-04  9.63278636e-02  4.76365648e-02  7.17942556e-03
  6.73971996e-02  8.78104270e-02 -6.69827089e-02  4.48983237e-02
  6.52936846e-03 -3.54665443e-02 -3.03517189e-02  1.17886931e-01
  1.11806309e-02  5.75354658e-02  1.07944325e-01 -3.12009938e-02
 -4.34361910e-03 -1.02502130e-01  2.28269235e-03 -4.19236049e-02
 -8.65418762e-02  6.29917607e-02  1.42672667e-02  9.93068963e-02
  1.86882466e-02 -4.16916460e-02 -2.63756942e-02 -4.80895527e-02
  6.74102381e-02  1.26994755e-02 -2.58851256e-02  1.16441841e-03
 -2.83390693e-02  4.69087772e-02 -8.89386460e-02  1.17214456e-01
 -4.90130708e-02  8.50011781e-02  5.04329726e-02  7.97401667e-02
 -3.40480730e-02 -9.28409025e-03 -3.23400162e-02 -2.97105182e-02
 -2.18578111e-02  7.48340227e-03  3.50366905e-02  7.65534490e-02
  3.63679091e-03 -8.76393728e-03 -5.39679900e-02 -8.94926861e-03
  2.55542751e-02 -8.56711194e-02  7.39100128e-02 -1.01772277e-02
  5.06889187e-02 -5.77215552e-02  1.08763754e-01  8.86224434e-02
 -1.00638144e-01 -4.33781563e-04  3.55937071e-02  7.96830431e-02
  3.91239524e-02 -5.61935827e-02 -5.23347743e-02  6.33870512e-02
  1.37038734e-02 -5.46685886e-03  1.20879829e-01  4.56836894e-02
  2.49027740e-02  2.20062714e-02 -4.43850942e-02  6.49596751e-02
  5.66047207e-02 -3.80126201e-02 -1.41943162e-02  2.73824460e-03
 -4.62801345e-02  2.14031403e-04  2.66881585e-02 -2.90125595e-08
 -2.07266044e-02 -2.29357393e-03  1.43914260e-02  1.28283305e-02
  2.58044731e-02 -3.93163227e-02  1.97586007e-02 -6.62034079e-02
  3.15700658e-03 -4.10897657e-02 -2.94914488e-02 -5.28193302e-02
 -1.54484482e-02  1.84753370e-02 -4.37786579e-02 -1.60001742e-03
 -6.69571608e-02 -1.37268290e-01  7.06132203e-02  2.67158300e-02
 -8.92345905e-02 -6.93245456e-02  7.67767206e-02  2.58473177e-02
 -9.75224189e-03 -7.58681968e-02 -7.55888224e-02 -3.27955559e-02
  2.73032133e-02  7.22597465e-02  9.37062688e-03  5.70929125e-02
  1.54058058e-02 -1.10566199e-01  1.01238817e-01 -1.19799338e-02
  3.54749747e-02  4.72090133e-02  1.97809488e-02  3.31544988e-02
 -1.26395049e-02 -1.15094269e-02  2.50637764e-03  3.37797850e-02
 -1.15062021e-01 -1.26511127e-01  1.94767788e-02  5.81021346e-02
  6.29420131e-02 -8.53301808e-02  3.45355412e-03 -2.29442231e-02
 -4.97415289e-02  7.19962418e-02 -1.47791188e-02 -7.20020607e-02
 -6.01821020e-02  2.44829468e-02 -6.81780726e-02  6.94663730e-03
  3.86995524e-02 -1.33975968e-01 -9.01915357e-02  6.46931231e-02]

In [19]:
print(embedding.shape)

(384,)

In [20]:
embeddings = model.encode(
    df["content"].tolist(),
    batch_size=32,
    show_progress_bar=True,
    convert_to_numpy=True
)

Batches:   0%|          | 0/3750 [00:00<?, ?it/s]

In [21]:
import numpy as np

np.save("document_embeddings.npy", embeddings)

In [22]:
!pip install -q faiss-cpu

In [23]:
import faiss
import numpy as np

In [24]:
dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

print("FAISS index created")

FAISS index created

In [25]:
index.add(embeddings)
print("Total vectors:", index.ntotal)

Total vectors: 120000

In [43]:
def semantic_search(query, top_k=5, threshold=0.45):

    query = query.strip()

    if not query:
        return []

    # Query embedding
    query_embedding = model.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    ).astype("float32")

    # FAISS search
    scores, indices = index.search(
        query_embedding,
        top_k
    )

    results = []

    for score, idx in zip(scores[0], indices[0]):

        # Important relevance filter
        if float(score) < threshold:
            continue

        row = final_df.iloc[int(idx)]

        results.append({
            "document_id": int(row["document_id"]),
            "category": row["category"],
            "title": row["title"],
            "content": row["content"],
            "keywords": row["keywords"],
            "score": float(score)
        })

    return results

In [44]:
semantic_search("artificial inteligence")

[{'document_id': 742,
  'category': 'Business',
  'title': "Computers with multiple personalities The jury's still out on whether a computer can ever truly be intelligent, but there's no question that it can have multiple personalities",
  'content': 'computers with multiple personalities the jury s still out on whether a computer can ever truly be intelligent but there s no question that it can have multiple personalities it s just a matter of software',
  'keywords': '',
  'score': 0.4722561836242676},
 {'document_id': 554,
  'category': 'Science & Technology',
  'title': 'NASA Develops Robust Artificial Intelligence for Planetary Rovers NASA is planning to add a strong dose of artificial intelligence (AI) to planetary rovers to make them much more self-reliant, capable of making basic decisions during a mission',
  'content': 'nasa develops robust artificial intelligence for planetary rovers nasa is planning to add a strong dose of artificial intelligence ai to planetary rovers to make them much more self reliant capable of making basic decisions during a mission scientists are developing very complex ai software that enables a higher level of robotic intelligence',
  'keywords': '',
  'score': 0.4684540629386902}]

In [45]:
threshold=0.45

In [46]:
results = semantic_search(
    "artificial intelligence",
    top_k=5,
    threshold=0.45
)

for r in results:
    print("Category:", r["category"])
    print("Title:", r["title"])
    print("Score:", r["score"])
    print("-" * 60)

Category: Science & Technology
Title: NASA Develops Robust Artificial Intelligence for Planetary Rovers NASA is planning to add a strong dose of artificial intelligence (AI) to planetary rovers to make them much more self-reliant, capable of making basic decisions during a mission
Score: 0.5102806687355042
------------------------------------------------------------
Category: Science & Technology
Title: NASA Software Allows Satellites to Troubleshoot in Space Goddard Space Flight Center -- NASA scientists recently successfully radioed artificial intelligence (AI) software to a satellite
Score: 0.4800454378128052
------------------------------------------------------------

In [47]:
results = semantic_search(
    "xyzabc123 moon pizza helicopter",
    top_k=5,
    threshold=0.45
)

print("Number of results:", len(results))

Number of results: 0

In [ ]:
import gradio as gr


def search_articles(query):

    if not query.strip():
        return "⚠️ Please enter a search query."

    results = semantic_search(
        query,
        top_k=5,
        threshold=0.45
    )

    if len(results) == 0:
        return """
## ❌ No Relevant Results

I couldn't find a sufficiently relevant article
for your search.

Try searching about:
- 🏏 Cricket / Sports
- 💼 Business / Stock Market
- 🌍 World News
- 💻 Technology / AI
"""

    output = f"## 🔎 Search Results for: `{query}`\n\n"

    for i, r in enumerate(results):

        output += f"""
### {i+1}. {r["title"]}

**Category:** `{r["category"]}`
**Similarity Score:** `{r["score"]:.3f}`

**Content:**
{r["content"]}

---

"""

    return output


with gr.Blocks(
    title="Semantic Search System"
) as demo:

    gr.Markdown("""
# 🔎 Semantic Search System

### Search news articles based on semantic meaning

Enter a query below and find the most relevant articles.
""")

    query = gr.Textbox(
        label="Search Query",
        placeholder="Example: artificial intelligence",
        lines=2
    )

    search_btn = gr.Button(
        "🔍 Search",
        variant="primary"
    )

    output = gr.Markdown()

    search_btn.click(
        fn=search_articles,
        inputs=query,
        outputs=output
    )

    query.submit(
        fn=search_articles,
        inputs=query,
        outputs=output
    )


demo.launch(
    share=True,
    debug=True
)

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://d8fc9bf5e8f8982672.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)